services:
  - type: web
    name: django-app
    env: python
    buildCommand: "./build.sh"
    startCommand: "gunicorn jobportal.wsgi:application"

services:
  - type: web
    name: jobportal
    env: python
    buildCommand: |
      pip install -r requirements.txt
      python manage.py migrate
      python manage.py loaddata users.json
      python manage.py collectstatic --noinput
    startCommand: gunicorn jobportal.wsgi:application
